env:
  node: true
  es6: true
  mocha: true
  browser: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 6
globals:
  Peer: true
  Comms: true
  Paxos: true
rules:
  no-native-reassign:
    - error
    - exceptions:
      - self
  no-console: 0
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
